%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Users\Lewis\Documents\MATLAB\LPSC\memberData.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2018/12/22 14:14:02

%% Initialize variables.
filename = 'C:\Users\Lewis\Documents\MATLAB\LPSC\memberData.csv';
delimiter = ',';
startRow = 2;
endRow = 2920;

%% Format for each line of text:
%   column1: double (%f)
%	column2: categorical (%C)
%   column3: text (%q)
%	column4: text (%q)
%   column5: text (%q)
%	column6: text (%q)
%   column7: categorical (%C)
%	column8: double (%f)
%   column9: categorical (%C)
%	column10: text (%q)
%   column11: categorical (%C)
%	column12: double (%f)
%   column13: datetimes (%{dd/MM/yyyy}D)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%C%q%q%q%q%C%f%C%q%C%f%{dd/MM/yyyy}D%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow-startRow+1, 'Delimiter', delimiter, 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines', startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
memberData = table(dataArray{1:end-1}, 'VariableNames', {'ID','uniorg','interests','subject','grad_date','course_level','branch_name','age','gender','space_word','mtype','status','registration_date'});

% For code requiring serial dates (datenum) instead of datetime, uncomment
% the following line(s) below to return the imported dates as datenum(s).

% memberData1.registration_date=datenum(memberData1.registration_date);

%% Clear temporary variables
clearvars filename delimiter startRow endRow formatSpec fileID dataArray ans;